export const FETCH_TRENDS = 'FETCH_TRENDS';
export const FETCH_TRENDS_RESOLVE = 'FETCH_TRENDS_RESOLVE';
export const FETCH_TRENDS_REJECT = 'FETCH_TRENDS_REJECT';
export const UPDATE_TRENDS = 'UPDATE_TRENDS';
export const CREATE_BOOKMARK = 'CREATE_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
